/* DELETE 'jdodb' database*/
DROP SCHEMA IF EXISTS jdodb;
/* DELETE USER 'lab' AT LOCAL SERVER*/
DROP USER IF EXISTS 'lab'@'%';

/* CREATE ''jdodb' DATABASE */
CREATE SCHEMA jdodb;
/* CREATE THE USER 'lab' AT LOCAL SERVER WITH PASSWORD 'lab' */
CREATE USER IF NOT EXISTS 'lab'@'%' IDENTIFIED BY 'lab';
/* GRANT FULL ACCESS TO THE DATABASE FOR THE USER 'lab' AT LOCAL SERVER*/
GRANT ALL ON jdodb.* TO 'lab'@'%';
